In [1]:
import pandas as pd
import numpy as np
import nltk 

In [2]:
movies = pd.read_csv("movie_dataset.csv")
from nltk.corpus import stopwords
stop = stopwords.words('english')

In [3]:
movies.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [4]:
#Feature Engineering
movies_cleaned = movies.drop(columns=['homepage','production_countries'])
features = ['keywords', 'cast', 'genres', 'director']
for feature in features:
    movies_cleaned[feature] = movies_cleaned[feature].fillna('')
def combined_features(row):
    return row['keywords']+" "+row['cast']+" "+row['genres']+" "+row['director']
movies_cleaned["combined_features"] = movies_cleaned.apply(combined_features, axis =1)
pat = r'\b(?:{})\b'.format('|'.join(stop))
movies_cleaned['overview_without_stopwords'] = movies_cleaned['overview'].str.replace(pat, '')
movies_cleaned['overview_without_stopwords'] = movies_cleaned['overview_without_stopwords'].str.replace(r'\s+', ' ')

<ipython-input-4-e580fef7c9a8>:10: FutureWarning: The default value of regex will change from True to False in a future version.
  movies_cleaned['overview_without_stopwords'] = movies_cleaned['overview'].str.replace(pat, '')
<ipython-input-4-e580fef7c9a8>:11: FutureWarning: The default value of regex will change from True to False in a future version.
  movies_cleaned['overview_without_stopwords'] = movies_cleaned['overview_without_stopwords'].str.replace(r'\s+', ' ')


In [5]:
movies_cleaned.head()

index     budget                                    genres      id  \
0      0  237000000  Action Adventure Fantasy Science Fiction   19995   
1      1  300000000                  Adventure Fantasy Action     285   
2      2  245000000                    Action Adventure Crime  206647   
3      3  250000000               Action Crime Drama Thriller   49026   
4      4  260000000          Action Adventure Science Fiction   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   
4  John Carter is a war-weary, former military ca...   43.926995   

                                production_companies  ...    status  \
0  [{"name": "Ingenious Film Partners", "id": 289...  ...  Released   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...  ...  Released   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...  ...  Released   
3  [{"name": "Legendary Pictures", "id": 923}, {"...  ...  Released   
4        [{"name": "Walt Disney Pictures", "id": 2}]  ...  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  \
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron   
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski   
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes   
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan   
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton   

                                   combined_features  \
0  culture clash future space war space colony so...   
1  ocean drug abuse exotic island east india trad...   
2  spy based on novel secret agent sequel mi6 Dan...   
3  dc comics crime fighter terrorist secret ident...   
4  based on novel mars medallion space travel pri...   

                          overview_without_stopwords  
0  In 22nd century, paraplegic Marine dispatched ...  
1  Captain Barbossa

In [6]:
#TFIDF Plot Based Filtering
from sklearn.feature_extraction.text import TfidfVectorizer
tfv = TfidfVectorizer(min_df=3,  max_features=None,
            strip_accents='unicode', analyzer='word',token_pattern=r'\w{1,}',
            ngram_range=(1, 3),
            stop_words = 'english')

In [7]:
tfv_matrix = tfv.fit_transform(movies_cleaned['overview_without_stopwords'].values.astype('U'))

In [8]:
from sklearn.metrics.pairwise import sigmoid_kernel

In [9]:
sig = sigmoid_kernel(tfv_matrix, tfv_matrix)

In [10]:
indices = pd.Series(movies_cleaned.index, index=movies_cleaned['original_title']).drop_duplicates()

In [11]:
def give_recomendationsivdfpf(title, sig=sig):
    idx = indices[title]
    sig_scores = list(enumerate(sig[idx]))
    sig_scores = sorted(sig_scores, key=lambda x: x[1], reverse=True)
    sig_scores = sig_scores[1:11]
    movie_indices = [i[0] for i in sig_scores]
    return movies_cleaned['original_title'].iloc[movie_indices]

In [12]:
give_recomendationsivdfpf('The Dark Knight')

3                         The Dark Knight Rises
299                              Batman Forever
428                              Batman Returns
3854    Batman: The Dark Knight Returns, Part 2
1181                                        JFK
1359                                     Batman
2507                                  Slow Burn
879                         Law Abiding Citizen
119                               Batman Begins
205          Sherlock Holmes: A Game of Shadows
Name: original_title, dtype: object

In [13]:
#Cosine Similarity With Plot Based Filtering
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [14]:
cv = CountVectorizer()
count_matrix = cv.fit_transform(movies_cleaned["overview_without_stopwords"].values.astype('U'))
print("Count Matrix:", count_matrix.toarray())

Count Matrix: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [15]:
cosine_sim = cosine_similarity(count_matrix)
print(cosine_sim)

[[1.         0.         0.         ... 0.         0.         0.        ]
 [0.         1.         0.04260143 ... 0.03311331 0.         0.        ]
 [0.         0.04260143 1.         ... 0.02680281 0.         0.        ]
 ...
 [0.         0.03311331 0.02680281 ... 1.         0.04003204 0.02041241]
 [0.         0.         0.         ... 0.04003204 1.         0.05883484]
 [0.         0.         0.         ... 0.02041241 0.05883484 1.        ]]


In [16]:
def getrecomcosp(title):
    movie_index = movies_cleaned[movies_cleaned.title == title]["index"].values[0]
    similar_movies = list(enumerate(cosine_sim[movie_index]))
    sorted_similar_movies = sorted(similar_movies, key=lambda x:x[1], reverse=True)
    i=0
    for movie in sorted_similar_movies:
        print(movies_cleaned[movies_cleaned.index == movie[0]]["title"].values[0])
        i=i+1
        if i>15:
            break

In [17]:
getrecomcosp('The Dark Knight')

The Dark Knight
The Dark Knight Rises
Batman
Batman: The Dark Knight Returns, Part 2
Batman Returns
Batman Forever
Batman Begins
Blackhat
Despicable Me 2
JFK
The Railway Man
Puss in Boots
The Man from U.N.C.L.E.
Inglourious Basterds
The Transporter Refueled
Django Unchained


In [18]:
#Meta Data Based Filtering With TfIDF
tfv2 = TfidfVectorizer(min_df=3,  max_features=None,
            strip_accents='unicode', analyzer='word',token_pattern=r'\w{1,}',
            ngram_range=(1, 3),
            stop_words = 'english')

In [19]:
tfv_matrix2 = tfv2.fit_transform(movies_cleaned['combined_features'].values.astype('U'))

In [20]:
sig2 = sigmoid_kernel(tfv_matrix2, tfv_matrix2)

In [21]:
indices2 = pd.Series(movies_cleaned.index, index=movies_cleaned['original_title']).drop_duplicates()

In [22]:
def give_recomendationsivdfmf(title, sig=sig):
    idx = indices2[title]
    sig_scores = list(enumerate(sig[idx]))
    sig_scores = sorted(sig_scores, key=lambda x: x[1], reverse=True)
    sig_scores = sig_scores[1:11]
    movie_indices = [i[0] for i in sig_scores]
    return movies_cleaned['original_title'].iloc[movie_indices]

In [23]:
give_recomendationsivdfmf('The Dark Knight')

3                         The Dark Knight Rises
299                              Batman Forever
428                              Batman Returns
3854    Batman: The Dark Knight Returns, Part 2
1181                                        JFK
1359                                     Batman
2507                                  Slow Burn
879                         Law Abiding Citizen
119                               Batman Begins
205          Sherlock Holmes: A Game of Shadows
Name: original_title, dtype: object

In [24]:
#Metadata based Filtering With Cosine Similarity
cv2 = CountVectorizer()
count_matrix2 = cv2.fit_transform(movies_cleaned["combined_features"])
print("Count Matrix:", count_matrix2.toarray())

Count Matrix: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [25]:
cosine_sim2 = cosine_similarity(count_matrix2)

In [26]:
def getrecomcosmf(title):
    movie_index = movies_cleaned[movies_cleaned.title == title]["index"].values[0]
    similar_movies = list(enumerate(cosine_sim2[movie_index]))
    sorted_similar_movies = sorted(similar_movies, key=lambda x:x[1], reverse=True)
    i=0
    for movie in sorted_similar_movies:
        print(movies_cleaned[movies_cleaned.index == movie[0]]["title"].values[0])
        i=i+1
        if i>15:
            break

In [32]:
getrecomcosmf('The Dark Knight')

The Dark Knight
The Dark Knight Rises
Batman Begins
Amidst the Devil's Wings
The Prestige
Kick-Ass
Kick-Ass 2
Batman Returns
Batman
The Killer Inside Me
Batman & Robin
Harry Brown
In Too Deep
Defendor
Point Blank
Harsh Times
